project:
  output-dir: docs

execute:
  echo: true
  freeze: false
  eval: false
  
book:  
  chapters:
    - index.qmd
    - part: "Methods"
      chapters:
      - Methods_ANIs.qmd
      - Methods_dDDH.qmd
      - Methods_Prokka_Annotations.qmd
      - Methods_Anvio.qmd
      - Methods_Figures.qmd
    - references.qmd
    - Methods_RSession.qmd